### ISSUE TITLE
Using LiDAR Classification of Vegetation instead of NDVI and "Gridded building roof heights" ?

### ISSUE THREAD

**Issue by KlatbahII** [markusmnzngr/LiDAR-3D-Urban-Forest-Mapping#1]
Hi i read your article, and tried your process with **my data on a little area**.  

## Data used

I have a **LiDAR with a density of 20 pts/m²**.  

|![lidar_classification](https://github.com/markusmnzngr/LiDAR-3D-Urban-Forest-Mapping/assets/98017942/73c89496-e426-4ec8-bd68-2411d5be3123)|
|:--:|
|*LiDAR i used display in CloudCompare. On this area, the dimension `Classification` have value from 1 to 6*|

I also have an **3DCityDB Database with buildings** on the area.  
I managed to create the csv with the **"Gridded building roof heights"**

|![zone_1](https://github.com/markusmnzngr/LiDAR-3D-Urban-Forest-Mapping/assets/98017942/1bfd9f06-81be-497e-a156-fd6a9bc56e6f)|
|:--:|
|*CSV file with "Gridded building roof heights" displayed in QGIS.*|

I don't have building models on all of the area where i want to use your process.  
I have an **IRC raster(RGB + NIR)** that i used to generate a **NDVI raster with a resolution of 50cm**.   

|![qgis_ndvi](https://github.com/markusmnzngr/LiDAR-3D-Urban-Forest-Mapping/assets/98017942/19734a66-7894-4e0f-96fa-014b43aad631)  |
|:--:|
|*NDVI raster displayed in QGIS*|

## Results 

I managed to get good results. So thanks a lot for your process.   

|![qgis_results](https://github.com/markusmnzngr/LiDAR-3D-Urban-Forest-Mapping/assets/98017942/4b8c9039-b78d-4325-b15f-f1514598acc6)  |
|:--:|
|*Results displayed in QGIS, i'm impressed with the delineation/delimitation of the crowns and the positioning of the trees.*|

But in the next picture, you can see the reason why i create this issue.  
I display here the LiDAR that is created by your process in the folder `urban_forest_classification`

|![lidar_results](https://github.com/markusmnzngr/LiDAR-3D-Urban-Forest-Mapping/assets/98017942/07fc614f-f3f3-4ea1-a3ac-974d4e55cc6f)|
|:--:|
|*Picture on top is the output lidar of your process with RGB displayed, and the picture on the bottom shows the dimension `Classification` of the LiDAR where Yellow is Vegetation(5) and Orange is Building(6)*|

## Possible improvement ?

But i noticed something that i *wanted to improve*.  
It is a *specific thing to the data i have at my disposal*.  
The LiDAR i have has a *really good point segmentation* in the dimension **Classification**.  
  
So i wanted to know if it's **possible to run your process without** :
- using the Gridded building roof heights and 
- using NDVI.  
  
And only use the LiDAR with my **Classification where the areas of vegetations are already "segmented"**.
I want to know if i can **use the points that have a value of `5(Vegetation)` in the dimension `Classification`**.  
Because after reading your paper, and running your process, what *i think i understood* is that the NDVI and the **"Gridded building roof heights"** are used to **define the "areas" of vegetations where the trees and the crowns** will be created.  

I ask you this, because when i looked at the results i found out that trees are **generated on wrong places, where the points in the LiDAR are classified as Building**.  
There is two issues that i found:

Trees and crown are generated where points are classified as Building(6)

|![issues_tree](https://github.com/markusmnzngr/LiDAR-3D-Urban-Forest-Mapping/assets/98017942/06140843-59ea-4d4c-8f72-0aaff96d2c0d)  |
|:--:|
|*The areas in yellow are where trees are false.*|

Crowns covers area where all the points are classified as Building(6)

|![issues_crown_building](https://github.com/markusmnzngr/LiDAR-3D-Urban-Forest-Mapping/assets/98017942/2453313c-b294-4ea8-af58-61ec5feb87ad)|
|:--:|
|*Crowns contains Building points. The little black and white points are the "Gridded building roof heights"*|

I hope my explanations are clear.  
If it's not and you're willing to respond let me know what you didn't understand.  
I've never used R before and managed to get your process running with my data, and i wanted to know if it's not too hard to do a little tweaks.

Thanks in advance

**Comment by markusmnzngr** [comment]
Hi Klatbahll, 

Thanks for your comment. I’m happy you could make use of the workflow. 

The whole workflow is sequential and the first steps where NDVI and roof heights are valuable information are mainly to classify tree points in the point cloud. 

So if you already have a good classification of tree points you could skip the first steps and filter your point cloud, rasterize it to a canopy height model and then run the parts where individual tree segmentation starts. 

For point cloud filtering and rasterization I would point you to the lidR package, from where I also use the functions. 
I hope I could help you and would close the issue because the code is specialized to give a classification of tree points in LiDAR data that aren’t already classified. 

Let me know if you have trouble adapting the code to your purpose.
