### ISSUE TITLE
Repeated error by 3DCityDB_rasterize_lod2_roof_heights.pgsql

### ISSUE THREAD

**Issue by utbock** [markusmnzngr/LiDAR-3D-Urban-Forest-Mapping#3]
Dear Markus,

I am a PhD Student at the University of Trier and want to use the published tool for all of the Trier city area.
Therefore I portioned and sorted the datasets into 130 tiles according to DTK5_UTM. During server based processing with the 3dcitydb docker setup from [TUM](https://3dcitydb-docs.readthedocs.io/en/version-2022.2/impexp/docker.html) the '3DCityDB_rasterize_lod2_roof_heights.pgsql' script recurrently throws the same error in line 180:
`psql:/data/3dcity_impexp/3DCityDB_rasterize_lod2_roof_heights.pgsql:180: ERROR:  function st_3dintersection(geometry, geometry) does not exist`

As far as tested, running the pgsql in pgAdmin works.

Can you tell why?

Attached you find the associated files with terminal prompts and one of the gml files as .zip.
[psql_script_error.zip](https://github.com/user-attachments/files/16380023/psql_script_error.zip)

Kind regards

**Comment by markusmnzngr** [comment]
Dear Utbock,

I apologize for the late reply. Were you able to resolve the issue? Unfortunately, I couldn't reproduce the error on my end, but one possible cause might be a missing SFCGAL backend when setting up your database with the 3DCityDB Docker. The [ST_3DIntersection](https://postgis.net/docs/ST_3DIntersection.html) function requires this backend.

**Comment by utbock** [comment]
Dear Markus,

thank you for your reply. Pointing out the SFCGAL backend was the solution. The parameter was not set for the docker.

Kind regards

**Comment by markusmnzngr** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre E-Mail.
Ich bin bis einschließlich Freitag, den 04.11.2022, nicht im IÖR.

Ich melde mich gerne danach bei Ihnen.

Mit freundlichen Grüßen
Markus Münzinger

-----------------------------------------------------------------
 
Dear Sir or Madam,

thank you for your e-mail.
I'm out of office until November 4th, 2022.

I'm happy to be in touch with you afterwards.

Kind regards,
Markus Münzinger
